### ISSUE TITLE
Enable Issues for MicrosoftDocs/azure-docs

### ISSUE THREAD

**Issue by hongbo-miao** [Azure-Samples/active-directory-javascript-graphapi-v2#1]
I am reading the doc [Call the Microsoft Graph API from a JavaScript Single Page Application (SPA)](https://docs.microsoft.com/en-us/azure/active-directory/develop/guidedsetups/active-directory-javascriptspa)

I try to open an issue, so I go to
https://github.com/MicrosoftDocs/azure-docs

But obviously Issues is disabled. Please enable it, thanks!

![image](https://user-images.githubusercontent.com/3375461/28998868-722673ce-79ea-11e7-880d-a08c48a870d9.png)

(Moved from https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/107)

**Comment by jmprieur** [comment]
Thanks for your feedback @Hongbo-Miao. The pull request are for all the azure docs BTW.
@danieldobalian : how can customers/partners raise issues on the doc?

**Comment by danieldobalian** [comment]
@Hongbo-Miao The best way to leave feedback on our documentation is through a comment on the article.

**Comment by hongbo-miao** [comment]
Oh, yeah, I will use commenting. Thanks!
