### ISSUE TITLE
JS Quickstart automatically signs me in

### ISSUE THREAD

**Issue by BrioLichen** [Azure-Samples/active-directory-javascript-graphapi-v2#22]
I'm trying out the JS quickstart from the portal, but it just logs me in automatically. I don't want to use that account and want to use another. this is not a good experience for the user.

**Comment by alaahusseiny** [comment]
@BrioLichen  You could add the prompt option in the request options to prompt the user to select the account :


```js
var request = {
    scopes: ["user.read"],
    prompt: 'select_account',
}
```

You could refer to the documentation about this here : https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-prompt-behavior

**Comment by jennyf19** [comment]
Thanks @alaahusseiny !

**Comment by jennyf19** [comment]
@DarylThayil @sameerag Is this something that should be added automatically in the Quickstart? Or is there a reason why the prompt is not set? thx.

**Comment by BrioLichen** [comment]
@alaahusseiny thanks. setting the prompt to select_account worked.
