### ISSUE TITLE
How does this differ from the other samples?

### ISSUE THREAD

**Issue by BigBlueHat** [Azure-Samples/active-directory-javascript-graphapi-v2#43]
Specifically, how does this project differ (or not) from https://github.com/Azure-Samples/ms-identity-javascript-v2/?

The seem (code-wise) nearly identical, but they reference MS Identity vs. Azure Activity Directory.

Any details you can provide would be helpful.

Thanks!
🎩

**Comment by derisen** [comment]
@BigBlueHat the main difference is that this sample is using [implicit flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow) to acquire a token, while the sample you link is using [authorization code flow with PKCE](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) (which is deemed more secure). We continue maintaining this sample, but if possible we recommend using [https://github.com/Azure-Samples/ms-identity-javascript-v2/](https://github.com/Azure-Samples/ms-identity-javascript-v2/).

**Comment by BigBlueHat** [comment]
Thanks! That definitely help clarify. Much appreciated!
